### ISSUE TITLE
afFieldValueIs not working with Semantic UI dropdown field

### ISSUE THREAD

**Issue by lfilho** [fabienb4/meteor-autoform-semantic-ui#42]
Hey there, @fabienb4 

I think I've found another glitch...
I'm trying to use Autoform's `afFieldValueIs` helper (http://autoform.meteor.com/fieldvalues) but it seems to only work with pure Autoform fields... If I test it with a field that is a Semantic UI dropdown it doesn't work...

In other words, in the following cenario "Hello" won't show, but if I change it to a regular Autoform input field, it will:

```
{{> afQuickField name='my-semantic-ui-dropdown-field' options=myOptions}}
{{#if afFieldValueIs name='my-semantic-ui-dropdown-field' value='a-value-from-semantic-ui-dropdown'}}
        <div>Hello</div>
{{/if}}
```

**Comment by lfilho** [comment]
Likewise, `AutoForm.getFieldValue()` also seems not to be working.

https://github.com/aldeed/meteor-autoform/blob/master/api.md#autoformgetfieldvaluefieldname-formidclient

Thank you for your effort, dude :)

**Comment by fabienb4** [comment]
Semantic isn't updating the `semantic:ui-css` package as quickly as `semantic:ui` (still 3 versions behind). Some changes in Semantic 2.1.5 fixed the updating problems we had in the past.
Are you using `semantic:ui-css` by any chance? If so, try to switch to `semantic:ui`.

See: https://github.com/fabienb4/meteor-autoform-semantic-ui/blob/master/CHANGELOG.md#080-breaking

**Comment by lfilho** [comment]
No, I'm not:

``` bash
cat .meteor/packages | grep semantic
semantic:ui
useraccounts:semantic-ui
fabienb4:autoform-semantic-ui
sarasate:semantic-ui-datetimepicker
```

**Comment by lfilho** [comment]
And the versions:

``` bash
cat .meteor/versions| grep semantic
fabienb4:autoform-semantic-ui@0.9.0
sarasate:semantic-ui-datetimepicker@0.0.2
semantic:ui@2.1.6
semantic:ui-data@2.1.6
useraccounts:semantic-ui@1.13.0
```

**Comment by lfilho** [comment]
Were you able to reproduce this, @fabienb4 ? Thank you very much

**Comment by mbernath** [comment]
Hi there, 
I can confirm the same problem (with the same versions). Trying to investigate a bit...
Marc

**Comment by fabienb4** [comment]
I haven't had time to investigate yet. I'll take a look right now.

Can any of you provide a specific example, so I don't have to go through every possible uses to find the problem?

**Comment by mbernath** [comment]
@fabienb4:
Sure! Here is an example that I (very quickly) extracted and simplified. Hope it works...

Template HTML:

```
<template name="test">
 {{#autoForm id="import" name="importForm" type="insert" collection="Imports"}}

  {{> afQuickField name="type"}}

  {{#if afFieldValueIs name="type" value="csv"}}
    {{> afQuickField name="delimiter"}}
  {{/if}}

  <div>
    <input class="ui primary button" type="submit" value="Import"/>
  </div>

 {{/autoForm}}
</template>
```

Model JS:

```
Imports = new Mongo.Collection('imports');

ImportSchema = new SimpleSchema({
  type: {
    type: String,
    allowedValues: ['csv','xlsx'],
    label: 'Format',
    defaultValue: 'csv',
    autoform: {
      options: [{value: 'csv', label:'CSV'},{value: 'xlsx', label:'XLSX'}]
    }
  },
  delimiter: {
    type: String,
    label: 'Delimiter',
    allowedValues: ['comma','semicolon'],
    defaultValue: 'comma',
    optional: true,
    autoform: {
      options: [{value:'comma',label:'Comma'},{value:'semicolon',label:'Semicolon'}]
    }
  });

Imports.attachSchema(ImportSchema);
```

**Comment by fabienb4** [comment]
Thanks @mbernath! Worked like a charm (only a missing curly brace near the end).

Actually "worked like a charm" can be used to describe the tests too.
If I select `XLSX`, the `delimiter` field disappear. On a refresh, I can clearly see that the `type` field is shown first, then the `delimiter` field is shown (just after `type` is assigned `CSV`).

And if I add:

``` js
Template.test.events({
  "change input[name=type]"(event) {
    console.log(`AutoForm.getFieldValue("type", "import") =>`, AutoForm.getFieldValue("type", "import"));
  }
});
```

The field value gets printed correctly in the console every time I change the selected value.

As both of you reported it, I don't doubt there is something wrong, but it looks like a conflict of some kind. Maybe you both are in a very specific case that I can't reproduce. (It's good for my sanity I guess, because I made sure that Autoform functions like these were working before I released 0.9.0.)

Can you try again with only the following in a test project and tell me if it still doesn't work?

`packages`:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifiers      # JS/CSS minifiers run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)

aldeed:simple-schema
aldeed:collection2
aldeed:autoform
semantic:ui
flemay:less-autoprefixer
fabienb4:autoform-semantic-ui
```

`client/af-semantic-ui.html`:

``` html
<head>
</head>

<body>
  {{> test}}
</body>

<template name="test">
 {{#autoForm id="import" name="importForm" type="insert" collection="Imports"}}

  {{> afQuickField name="type"}}

  {{#if afFieldValueIs name="type" value="csv"}}
    {{> afQuickField name="delimiter"}}
  {{/if}}

  <div>
    <input class="ui primary button" type="submit" value="Import"/>
  </div>

 {{/autoForm}}
</template>
```

`client/af-semantic-ui.js`:

``` js
Template.test.events({
  "change input[name=type]"(event) {
    console.log(`AutoForm.getFieldValue("type", "import") =>`, AutoForm.getFieldValue("type", "import"));
  }
});
```

`lib/collection.js`:

``` js
Imports = new Mongo.Collection('imports');

ImportSchema = new SimpleSchema({
  type: {
    type         : String,
    allowedValues: ['csv', 'xlsx'],
    label        : 'Format',
    defaultValue : 'csv',
    autoform     : {
      options: [
        {
          value: 'csv',
          label: 'CSV'
        }, {
          value: 'xlsx',
          label: 'XLSX'
        }
      ]
    }
  },
  delimiter: {
    type         : String,
    label        : 'Delimiter',
    allowedValues: ['comma', 'semicolon'],
    defaultValue : 'comma',
    optional     : true,
    autoform     : {
      options: [
        {
        value: 'comma',
        label: 'Comma'
        },
        {
          value: 'semicolon',
          label: 'Semicolon'
        }
      ]
    }
  }
});

Imports.attachSchema(ImportSchema);
```

For information:
`versions`:

```
aldeed:autoform@5.8.1
aldeed:collection2@2.6.1
aldeed:simple-schema@1.5.0

fabienb4:autoform-semantic-ui@0.9.0

semantic:ui@2.1.6
semantic:ui-data@2.1.6
```

**Comment by mbernath** [comment]
@fabienb4 
Ok, I can confirm the example works like a charm in an isolated project. In my main project no change events at all are emitted for that form. I'll try to investigate this further. Any ideas?

**Comment by mbernath** [comment]
Still no solution, but some insights.

When I add an onChange event handler to select.js as it was discussed in commit 257336a621686ec8287b7b2ec863ccddbc69e8c0, at least the valueOut method is called. But that still does not resolve the problem.

```
node.dropdown(_.extend({
    fullTextSearch        : this.data.atts.fullTextSearch || false,
    allowAdditions        : this.data.atts.allowAdditions || false,
    maxSelections         : this.data.atts.maxSelections || false,
    allowCategorySelection: this.data.atts.allowCategorySelection || false,
    useLabels             : this.data.atts.useLabels === false ? false : true,
    debug: true,
    onChange               : function (event) {
            node.trigger("change", { target: node });
        }
}, this.data.atts.settings));
```

**Comment by lfilho** [comment]
Sorry guys, I've been fairly sick since yesterday, so I'm low on energy... I'll try to investigate a bit more too

**Comment by mbernath** [comment]
Got it!

The reason was that I updated the semantic:ui package, but updating the package does not trigger a rebuilt of all Semantic JS files. Therefore the Semantic code base was still outdated.

Solution: Delete all files from your `some-path-to-your/semantic-ui` folder except your custom files and the `custom.semantic.json`. Then restart the app and it should work.

@fabienb4: You were right. Thanks very much for helping!!

**Comment by lfilho** [comment]
Ooh! Superb, @mbernath ! That was indeed it!

But I think we only need to remove the hidden `.custom.semantic.json` in order to trigger the rebuild.

Thanks guys! Long live this repo! :sweat_smile: I'll go ahead and close this issue then

**Comment by fabienb4** [comment]
I'm glad you found and fixed the problem guys!
I took the liberty of reporting it in the Semantic-UI package.

**Comment by lfilho** [comment]
Great job, thanks!
